completed css-two-column-layout. katiefugate.
katiefugate/c0321-code-solutions pull request #20
Opened 2021-03-14 00:56 UTC by katiefugate

<img width="993" alt="Screen Shot 2021-03-13 at 4 54 24 PM" src="https://user-images.githubusercontent.com/78885956/111053933-005dd700-841d-11eb-9e50-6267934d91f5.png">

2021-03-15 22:34 UTC, codingcodymiller requested changes
Great start!! Please see my notes

2021-03-15 22:34 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  padding-right: 225px;
Instead of doing this, I would set a `width` on this element, and use `margin: auto` to center it

2021-03-15 22:34 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  left: 400px;
Instead of doing this large movement, you should set `text-align: center` on the parent element for this button.

2021-03-15 22:59 UTC, katiefugate commented
![Screen Shot 2021-03-15 at 3 57 57 PM](https://user-images.githubusercontent.com/78885956/111232014-79893580-85a7-11eb-8b7a-705bd1b40094.png)

2021-03-16 00:14 UTC, codingcodymiller approved these changes
Great work!!

2021-03-16 00:29 UTC, merged