completed javascript-modal. katiefugate.
katiefugate/c0321-code-solutions pull request #45
Opened 2021-03-23 22:10 UTC by katiefugate

![Screen Shot 2021-03-23 at 3 09 04 PM](https://user-images.githubusercontent.com/78885956/112225388-f3de3900-8be9-11eb-8f2d-84314148bf1c.png)
![Screen Shot 2021-03-23 at 3 09 16 PM](https://user-images.githubusercontent.com/78885956/112225391-f476cf80-8be9-11eb-8d84-0ea33256eec6.png)

2021-03-23 22:36 UTC, codingcodymiller requested changes
Great work so far!! Please see my notes

2021-03-23 22:36 UTC, codingcodymiller commented on javascript-modal/style.css
> +  position: absolute;
This button should be in the normal document flow, it shouldn't be absolute positioned. You could absolute or fixed position the modal, that is the content meant to sit on a layer above normal content.

2021-03-23 22:36 UTC, codingcodymiller commented on javascript-modal/index.html
> +<dialog class="modal">
Very cool usage of the `dialog` element!! Unfortunately, the `dialog` element still isn't well-incorporated across all browsers, so you won't want to make use of it just yet. I recommend looking back to the `fixed` portion of the `css-positioning` exercise for some tips on how to accomplish this without a `dialog` element

https://caniuse.com/dialog

2021-03-24 00:04 UTC, katiefugate commented
![Screen Shot 2021-03-23 at 5 01 51 PM](https://user-images.githubusercontent.com/78885956/112234481-d9ac5700-8bf9-11eb-889d-a65be9cc90ed.png)
![Screen Shot 2021-03-23 at 5 02 02 PM](https://user-images.githubusercontent.com/78885956/112234482-da44ed80-8bf9-11eb-9f33-ea5d0b348ce4.png)

2021-03-24 01:06 UTC, codingcodymiller approved these changes

2021-03-24 01:07 UTC, merged